### PR TITLE
Deprecate py27 (linux), add py39 (osx)

### LINKED ISSUE #1334: Python wheel builds failing on catalina for py36 and py38
https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=2147&view=results

We should `pip install -U` wheel [here](https://github.com/finos/perspective/blob/1725f48d6b15fc5927a34524910ab65c47ceef76/scripts/_wheel_python.js#L67) and see if that helps.

Should also add it as a dev dependency [here](https://github.com/finos/perspective/blob/1725f48d6b15fc5927a34524910ab65c47ceef76/python/perspective/setup.py#L77).

### PR DESCRIPTION
**Pull request by timkpaine**
Fixes #1334, adds py39 now that brew defaults this on OSX.

### CODE REVIEW

**Comment by timkpaine** [comment]
builds all passing except the 2 that require docker changes, so looks good

**Review by sc1f — APPROVED** [review]
Looks good - will need a rebuild of the Docker images, and a full tagged build run to check if the wheel builds work.

**Review by texodus — CHANGES_REQUESTED** [review]
The `Dockerfile` modifications in this file do not build - it appears as if the method on step 42 for acquiring `nodejs` via `yum` has bit-rotted, which I recognize was not touched by this PR, but nonetheless ...

The experience of discovering this after >1hr of `docker build`, suggests strongly to me we need a better method of building Python, perhaps we build these images exclusively from Azure?  Are these images needed still now that the `pyarrow` dependency has been removed? 

Regardless, two things are true, (1) I cannot merge this PR until the `Dockerfile` builds, and (2) addressing this tech debt must pre-empt any future image dists.

**Comment by timkpaine** [comment]
I've updated and tested building the docker images from scratch. They are necessary as azure does not provide a `manylinux` compatible environment, so in order to dist linux wheels we need these docker images.

**Comment by timkpaine** [comment]
(I've also dropped python2 in these last changes)

**Comment by texodus** [comment]
> (I've also dropped python2 in these last changes)

Nice try - I've refactored these changes to #1374

**Review by texodus — APPROVED** [review]

**Comment by texodus** [comment]
Upon further review, the `pypa/manylinux2010_x86_64` container we relied upon is now non-reproducible, as the upper-bound of python2 compatible versions is above the lower-bound of CentOS 6 compatible versions.  This makes python2 effectively deprecated, even if this image was preserved.

Which means that `0.6.2` is the last python2 "compatible" version that will be published - insofar as `perspective-python` can be compatible with a language whose own support has been deprecated.

**Pull request merged**
