### PR TITLE
Run ESLint on documentation + minor documentation improvements

### PR DESCRIPTION
**Pull request by sc1f**
This PR adds `eslint-plugin-markdown` and applies auto-formatting fixes to Javascript code blocks in our markdown documentation.

Additionally it fixes some formatting issues with the Python documentation, adds `PerspectiveTornadoHandler` to the Python documentation, as well as fixes typos, makes improvements & adds examples to both JS and Python docs.

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@ibhanu).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@ibhanu).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by texodus** [comment]
Thanks for the PR!

**Comment by texodus** [comment]
Agh, I meant to leave a review before I merged that - so I'll do so posthumously.

Thanks alot @ibhanu, and thanks @sc1f for automating this process!  The automation is really important I think, given the power of tools like `eslint` today, it seems silly not to automate anything we feel strongly enough about to auto-format in the first place!

**Pull request merged**
