### PR TITLE
fix "Data" to "Heatmap" axes transposing-1127

### PR DESCRIPTION
**Pull request by zxy994**
#1127 Datagrid gets transposed (axis are swapped) when plugin is changed from "Grid" to "Heatmap" #1127

[https://github.com/finos/perspective/issues/1127]

BEFORE:

https://user-images.githubusercontent.com/38087267/231719273-e1d65e1b-f7d3-4bae-b517-8d51200530aa.mp4

AFTER:

https://user-images.githubusercontent.com/38087267/231719332-166b59bb-da4c-4294-a1d3-fcdb5244e7d1.mp4

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @maoo and @texodus - Would it be possible to review this PR and kick off the GitHub Action below to help unblock and merge @zxy994's PR. Many thanks!

https://github.com/finos/perspective/actions/runs/4687813968

Screenshot 2023-04-18 at 11 00 31

**Comment by texodus** [comment]
@zxy994 @mcleo-d This PR is much appreciated! 

... but the issue it stems from is out-of date. I [posted a comment in the original issue](https://github.com/finos/perspective/issues/1127#issuecomment-1505278556) explaining the reasoning here , #2113 is the correct fix which pre-dates this PR.

I apologize, this was extremely sloppy book-keeping on my end:

* I should've updated the issue sooner.
* #2113 I merged didn't close the issue or contain a description (I'll rectify this).

We're committed to making this situation better - clean up the backlog, publish a roadmap, create a chatroom community.

Back to the PR - @zxy994 I unfortunately [can't merge it](https://github.com/finos/perspective/issues/1127#issuecomment-1505278556) as-is, but if you're willing to push this change a bit further, I would like to preserve the functionality for another feature we're about to contribute from [Prospective Co.](https://www.prospective.co/) - Chart Config UI. While this feature won't be ready for a bit longer, if I can have this PR off-by-default, I can merge it now and re-enable it when there is a configuration screen implemented for the chart type. I would accept either of 2 forms of this -

1. Easy mode - feature flag. Just put a conditional around this functionality which defaults to `false`.  We will write a new Issue describing the next steps and re-enable this later.
2. Hard mode - `plugin_config`. Perspective plugins have their own custom persistence layer represented by the `plugin_config` config key.  We could add a custom settings for heatmaps (e.g. `invert_axis`) that is `false` by default and allows adventurous users to enable this functionality through the [Plugin API](https://github.com/finos/perspective/blob/master/rust/perspective-viewer/src/ts/plugin.ts#L161). This is the same general idea as a feature flag, but involves wiring the state change through a few additional files.

If this is out of scope, we can reconsider this PR when we have a configuration screen to support it.

**Review by texodus — CHANGES_REQUESTED** [review]
As per comment - we need (at least) feature-flagged off.

**Comment by zxy994** [comment]
@texodus Thanks for the review! I'll proceed to adding a conditional around this functionality which defaults to false.

**Comment by texodus** [comment]
Apologies, we're going to be taking this component in a different direction and this PR will be immediately squashed by this work, so closing (its non functional regardless)

**Comment by zxy994** [comment]
@texodus Sure!

**Pull request closed without merging**
