### PR TITLE
Implement `to_arrow` in C++ for JS/Python

### PR DESCRIPTION
**Pull request by sc1f**
This PR uses the C++ Apache Arrow library to serialize Perspective views into the Arrow format. It includes:

- *Upgrade Arrow to `0.15.1`*, which requires a rebuild of Docker images.
- Serialize to arrow for 0, 1, and 2-sided contexts, respecting start/end row and column.
- Generate row delta (changed rows after `update()`) using C++ to_arrow, and implemented in Python.
- Fix issue with `WebsocketClosedError` breaking in streaming example - clients closing websocket should no longer break lingering callbacks.
- Refactor `PerspectiveManager` to use `_PerspectiveCallbackCache` instead of a dictionary.
- add `remote.py` example in Python, which uses `to_arrow` and `row_delta` to stream changed rows to clients every millisecond.
- Splitting `arrow.cpp` into `arrow_loader` and `arrow_writer` for cleanliness.
- Removes `scalar_vec_to_val` and `scalar_vec_to_string` methods in C++ - use `scalar_to_val` instead.

### CODE REVIEW

**Comment by texodus** [comment]
`to_arrow()` performance in Javascript on this branch is nearly a 2x speedup!  Very nice!

Screen Shot 2019-12-28 at 4 50 29 AM

**Comment by texodus** [comment]
Also fixed longstanding [test flap](https://travis-ci.org/finos/perspective/jobs/630475178#L2051), which was due to incorrect Javascript `Date` API usage.

**Comment by RandomFractals** [comment]
This looks great! Can't wait to try it in JS. Are all the arrow date types properly handled in this update?

**Comment by sc1f** [comment]
Yes - date32 and date64 are handled as date types, while timestamp is handled as a datetime.

**Comment by RandomFractals** [comment]
sweet! will wait for the next rc to bundle it in my data ext. that uses this lib. 

would be a nice way to close this year & thank you guys for this awesome data analytics lib & contribs!

**Pull request merged**
