### PR TITLE
Invert heatmap y-axis

### PR DESCRIPTION
**Pull request by sinistersnare**

### CODE REVIEW

**Comment by sinistersnare** [comment]
@finos-admin @TheJuanAndOnly99 @mcleo-d

I have signed the CLA, your bot is broken

**Comment by TheJuanAndOnly99** [comment]
Hi @sinistersnare thanks for reaching out. I'm looking into it. Will get back to you as soon as possible.

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@sinistersnare all set

**Comment by texodus** [comment]
@sinistersnare I've rebased this in #2113, closing in favor of that PR

**Pull request closed without merging**
