### PR TITLE
Handle zero values in line plots

### LINKED ISSUE #1830: Handling of zero values in line plots
Hi,

I'm reporting a potential bug first observed by a user of Panel using the Perspective pane (https://github.com/holoviz/panel/issues/3577).

To reproduce the bug I've installed the Python version of Perspective (version `1.3.5`) and ran this code in JupyterLab:

```python
import pandas as pd
import perspective

data = {'x': [1,2,3], 'y': [1, 0, 3]}
df = pd.DataFrame(data)

w = perspective.PerspectiveWidget(data)
w
```

I then chose the `X / Y Line` representation. Hovering the 2nd point, at coordinates [2, 0], doesn't show any tooltip while a tooltip is displayed when the other points are hovered. Hovering that point gives the following error in the web console:

```
Uncaught TypeError: e.mainValues is undefined
    OO perspective-jupyterlab.js:1324
    OO perspective-jupyterlab.js:1324
    RO perspective-jupyterlab.js:1324
    a perspective-jupyterlab.js:1324
    r perspective-jupyterlab.js:1324
    rl perspective-jupyterlab.js:17
    r perspective-jupyterlab.js:1324
    c perspective-jupyterlab.js:1331
    o perspective-jupyterlab.js:1331
    call perspective-jupyterlab.js:17
    t perspective-jupyterlab.js:576
    gh perspective-jupyterlab.js:17
```

image

### PR DESCRIPTION
**Pull request by dev-navian**
resolved #1830 

### BEFORE:

before changes 1

before changes 2

### AFTER:

after changes 2

after changes

### CODE REVIEW

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by dev-navian** [comment]
Thank you @mcleo-d and @TheJuanAndOnly99

**Review by texodus — APPROVED** [review]
Thanks for the PR @dev-navian!  Looks good!

I would normally ask for a test for this type of change - however tooltips are quite difficult to test and the task is made artificially hard right now as we're in the process of upgrading the test suite.  I've verified by hand this fix appears to work and is a strict improvement over tooltips on this chart currently.

**Pull request merged**
