### PR TITLE
Add build for python 3.11

### PR DESCRIPTION
**Pull request by tomjakubowski**
Add support for python 3.11

### CODE REVIEW

**Comment by timkpaine** [comment]
https://github.com/conda-forge/perspective-feedstock/blob/main/recipe/meta.yaml#L37

**Comment by tomjakubowski** [comment]
Oh, is this going to break something on Windows?

**Comment by timkpaine** [comment]
> Oh, is this going to break something on Windows?

it might, needs to be tested on all platforms with full builds

**Review by texodus — CHANGES_REQUESTED** [review]
Thanks for the PR!

Let's go ahead and actually do 3.11 builds in GitHub Actions - no point in merging this separately.

**Comment by texodus** [comment]
lol I meant on Monday :)

[full build here](https://github.com/finos/perspective/blob/master/scripts/publish.js#L61)

We'll also need to update the [publish scripts](https://github.com/finos/perspective/blob/master/scripts/publish.js#L61) for these packages to actually be disted.

**Comment by texodus** [comment]
This looks like it's dying on Windows due to [some link error with boost](https://github.com/finos/perspective/actions/runs/4841715483/jobs/8628280629#step:22:924)

For posterity when this log is flushed, here's the first missing file:

> D:\a\perspective\perspective\python\perspective\dist\src\include\perspective/step_delta.h(22,10): fatal  error C1083: Cannot open include file: 'boost/variant/apply_visitor.hpp': No such file or directory (compiling source file D:\a\perspective\perspective\python\perspective\dist\src\cpp\binding.cpp) [D:\a\perspective\perspective\python\perspective\build\temp.win-amd64-cpython-38\Release\psp.vcxproj]

**Comment by texodus** [comment]
Cherry-picked pybind updates to #2234

**Pull request closed without merging**
