### PR TITLE
Restore firefox support by removing captrue group from regex pattern

### LINKED ISSUE #1047: Examples currently broken/wont load in firefox
### Steps to Reproduce:
1. Start up one of the examples
2. Open `localhost:8080` in firefox

### Expected Result:
A perspective example

### Actual Result:
Blank page, couple of errors in the console

### Environment:
OS X 10.14
Firefox 76

### Additional Context:
The offending line is here:

https://github.com/finos/perspective/blob/cafaec6009a11f77c49b2a3fd7936d8b2074ae85/packages/perspective-viewer/src/js/computed_expressions/lexer.js#L35

Chrome supports named capturing groups in a regex pattern, but firefox does not (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility)). This line causes an `SyntaxError: invalid regexp group` error to show up in the firefox console and the example pages to not load.

The capturing group isn't even used anywhere, so simply removing it from the pattern fixes the bug completely.

### PR DESCRIPTION
**Pull request by telamonian**
fixes #1047

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@telamonian).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by telamonian** [comment]
What the heck, didn't we already go through this last time? I'm already marked as a contributor

**Comment by texodus** [comment]
Thanks for the PR!

**Comment by texodus** [comment]
fixes #1048

**Comment by mcleo-d** [comment]
Hi @telamonian, 

I'm sorry you experienced issues with the CLA Bot during this contribution. 

Please feel reassured the CLA Bot is here to keep contributions into Perspective safe and we have now whitelisted you which lets the bot know you are an approved and trusted member of the team.

If you experience any further issues, please do email FINOS at help@finos.org as we're more than happy to help.

James.

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Pull request merged**
