### PR TITLE
Update CMakeLists.txt for more thread help on mac for conda

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by texodus** [comment]
Thanks @timkpaine - I moved the CI for this to a [full-build 3618](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=3618&view=results)

**Review by texodus — APPROVED** [review]
Thanks for the PR!  Looks good!

Just FYI - consolidating these small PRs (#1630 #1631 #1632 #1634 #1635 #1636) and providing a summary tremendously helps generate coherent `CHANGELOG.md` messages, which in turn makes the value proposition of new Perspective releases more clear.

Compare e.g. Perspective's changelog to [esbuild's](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md).

**Comment by timkpaine** [comment]
no prob, some people like small discrete PRs and some people like combined PRs, usually its the former.

I usually find this view helpful for release notes, since we have merge commits you can see all merged PRs since last release in the form `Merge pull request <link>`

https://github.com/finos/perspective/compare/v1.0.3...master

**Comment by texodus** [comment]
I don't disagree, I'd just like the merge PRs that show up in the log to tell a coherent story to the reader (I don't think you'd argue that e.g. "Fix ugly spacing" does that).  We're grateful for all PRs obviously and I'm not going to block merging them for poor metadata, and certainly in isolation there are non-functional PRs that we clearly want to merge that are not obviously merge-able with other open PRs.

I will note these issues them when I see them in the PR comments, and potentially re-do/re-submit egregious offenders as new PRs.

**Comment by timkpaine** [comment]
Yeah i usually rely on the tags to indicate whats going on (and `internal` isnt really something the end user cares about too much) but i'll go ahead and make some better titles so those show up at least

**Pull request merged**
