### PR TITLE
Aligning README and NOTICE file to FINOS guidelines

### PR DESCRIPTION
**Pull request by maoo**

### CODE REVIEW

**Comment by timkpaine** [comment]
We have a separate contributing document.
https://github.com/finos/perspective/blob/master/CONTRIBUTING.md

**Comment by timkpaine** [comment]
There's also a whole developers guide 
https://perspective.finos.org/docs/md/development.html

**Comment by timkpaine** [comment]
What benefit does the NOTICE provide that is not included in the other bits?

**Comment by maoo** [comment]
Hi @timkpaine , let me give you some context.

A NOTICE file must be present at the root of each project, and must contain the copyright notices of each copyright holder who has contributed to the project; you can [read more on our Wiki page](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-TheNOTICEfile)

The README.md should include the guidelines to apply for an (Individual or Corporate) CLA with FINOS, to avoid frictions with our CLA bot, which flags Pull Requests coming from new contributors; see the text below, feel free to add it anywhere in the README you think is appropriate.

_NOTE:_ Commits and pull requests to FINOS repositories will only be accepted from those contributors with an active, executed Individual Contributor License Agreement (ICLA) with FINOS OR who are covered under an existing and active Corporate Contribution License Agreement (CCLA) executed with FINOS. Commits from individuals not covered under an ICLA or CCLA will be flagged and blocked by the FINOS Clabot tool. Please note that some CCLAs require individuals/employees to be explicitly named on the CCLA. *Need an ICLA? Unsure if you are covered under an existing CCLA? Email [help@finos.org](mailto:help@finos.org)*

Hope this clarifies things a bit more.

**Comment by timkpaine** [comment]
@maoo it shouldnt go in the readme, it should go in the developer documentation. That can be found [here](https://github.com/finos/perspective/blob/master/docs/md/development.md) and gets autogenerated into the documentation

If theres a split copyright, then [this](https://github.com/finos/perspective/blob/master/LICENSE#L189) should be modified to read "Perspective Authors" and you can add the bit about finos to the [authors file](https://github.com/finos/perspective/blob/master/AUTHORS)

I'd rather avoid adding some unnecessary cruft files to the dist that don't follow the standard open source patterns.

**Comment by timkpaine** [comment]
Here's an example
https://github.com/pandas-dev/pandas/blob/master/AUTHORS.md

**Comment by copiesofcopies** [comment]
The NOTICE file is a convention and not essential if the same information is included in some other sensible place. The AUTHORS file here looks good.

**Pull request closed without merging**
