### PR TITLE
Coerce to float64 when user tries to pass in float32 as float64 - fixes #1717

### LINKED ISSUE #1717: float32 dtype in dataframe is parsed incorrectly
## Bug Report

Not sure if this is expected behavior, but was not very intuitive.
If perspective.Table has a `float` type, it only processes `float64` dtypes correctly.

### Steps to Reproduce:
```python
import numpy as np
import pandas as pd
from perspective import Table

values = [1.0, np.nan, 1.0]
df = pd.DataFrame({
    'float32': values,
    'float64': values,
}).astype({'float32': 'float32', 'float64': 'float64'})

t = Table({c: float for c in df.columns})
t.update(df)
pdf = t.view().to_df()

print('df', df)
print('pdf', pdf)
```

```python
df
    float32  float64
0      1.0      1.0
1      NaN      NaN
2      1.0      1.0
pdf
                                              float32 float64
0  2247116950146617980973935240244020099132744431...     1.0
1                                               None    None
2                                                0.0     1.0
```

### Expected Result:
Both float32 and float64 are parsed correctly.

### Actual Result:
Only float64 is parsed correctly.

### Environment:
perspective.__version__
'1.2.0'

### PR DESCRIPTION
**Pull request by justice-asare**
resolved #1717 

**Before**

image

 **After**
image

**Some extra tests**
image

image

### CODE REVIEW

**Comment by timkpaine** [comment]
These both work:
Screenshot 2023-04-14 at 11 24 00

You've explicitly told the table to use `float` (which is `float64`). I'm comfortable with these changes, which are more of a "help the user do the right thing" rather than a "fix", but they'll need tests added.

**Comment by justice-asare** [comment]
Could you please specify the tests that are required in more detail?

**Comment by timkpaine** [comment]
tests that cover the new code added

**Comment by justice-asare** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Review by timkpaine — APPROVED** [review]
There are likely more conversions for us to do outside the scope of the original ticket, but I'm happy with this change as is.

**Comment by justice-asare** [comment]
I'm glad to hear that you're satisfied with the current change.

**Comment by texodus** [comment]
@timkpaine I would like to see whatever changes you want in Issues if you can please!

**Comment by texodus** [comment]
Thanks for the PR! Looks good!

**Pull request merged**
