### PR TITLE
UI Redesign

### PR DESCRIPTION
**Pull request by texodus**
A redesigned UX by [Thought Merchants](https://www.thoughtmerchants.com/) and [the Prospective Co](https://prospective.dev/).  

[Superstore Demo](https://prospectiveco.github.io/tm-redesign-demo/).  

[screen](https://prospectiveco.github.io/tm-redesign-demo/)

UI changes:

* New themes, `Pro Light` and `Pro Dark`, replace `Material Light` and `Material Dark`.
    * New icons, new colors, new _attitude_.
* New plugin selector with fancy indicator icons.
* Move settings origin to the top-right corner.
* Moves the config selector controls (Group By, Split By, Order By, Where) to vertical orientation and places them above the column selector, with which it now shares a scroll panel.
* Aggregate selectors no longer expand the drag container.
* Expression delete button is now inside the expression dropdown.
* Adds a `title` persistence field, as well as an user-editable title control that persists when the settings panel closes if it is non-empty.
* `StatusBar` now shows total/virtual rows and total/virtual columns.
* Adds section labels for all plugins, including `perspective-viewer-datagrid`.
* Makes `Treemap` and `Sunburst` charts render when `Group By` is empty (even though this is not yet a particularly useful view due to the coupling of `Group By` with the axis label)

Non-UI changes:

* Switch to `serde_wasm_bindgen`, improves performance and asset payload.
* Refactor `ScrollPanel` to
     *  Take inconsistently-sized children.
     *  Scroll via `transform: translateY()` to reduce screen-shear.
* Adds `Table.num_rows` and `Table.num_columns` to `@finos/perspective`.

TODO:

* [ ] Missing axis-switching icons.
* [x] Missing boolean column icons.

### CODE REVIEW

**Comment by thoughtmerchant** [comment]
Looks great dude!

**Comment by timkpaine** [comment]
chrome:
Screenshot 2023-02-21 at 12 44 48

safari, settings button is present but behind
Screenshot 2023-02-21 at 12 44 45

**Comment by GREEB** [comment]
> chrome: Screenshot 2023-02-21 at 12 44 48
> 
> safari, settings button is present but behind Screenshot 2023-02-21 at 12 44 45
> 
> it has `opacity: 0` which is not being set to `1` during whatever event handler is in place

same for firefox 110.0

love the design!

**Comment by mhkeller** [comment]
In Firefox 110.0 I don't see the `Configure` button on the right side. It shows up in Chrome, though.
Screenshot 2023-02-21 at 4 21 29 PM

**Comment by texodus** [comment]
Thanks @timkpaine @mhkeller looks like [`:host-context` is only supported on Chrome](https://caniuse.com/?search=host-context).  This should be fixed now on the [updated demo](https://prospectiveco.github.io/tm-redesign-demo/).

Re: the positioning of the button, there is now an optional header displayed even when the config panel is closed which removes this overlap.  It can currently be enabled by giving the viewer a title:


https://user-images.githubusercontent.com/60666/220505199-cf7e4254-fc80-451b-a694-b4dee6656e4d.mov

**Comment by GREEB** [comment]
great design i like it a lot, there is a weird problem with the theme drop-down (export and copy drop-down work as expected)

after opening and closing the dropdown without choosing an option it seems to be in a weird state.
If choosing an option is seems fine. Firefox 110
firefox

**Comment by davisford** [comment]
This was some solid work.  Kudos to all the players that made this happen!

**Pull request merged**
