### PR TITLE
Allow users register multiple on_delete callbacks to view and table

### PR DESCRIPTION
**Pull request by zemeolotu**

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community. We require contributors to be identified and we couldn't parse GitHub user details of the following contributors: **Zeme Olotu**.

In order for your PR to be reviewed and merged, please follow the following directions:
1. check if your git client is configured with an email to sign commits `git config --list | grep email`
2. If not, set it up using `git config --global user.email email@example.com`
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails
4. Amend the authors in the commit history; use `git commit --amend` to only change last commit, or one between `git reset --soft` and `git rebase` to checkout changes, rewrite commit history locally and (force) push changes to the downstream branch

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If you still have any questions or just don't know what to do next, please email [help@finos.org](mailto:help@finos.org). /CC @finos-admin

**Comment by timkpaine** [comment]
@finos-admin please fix cla bot

**Comment by texodus** [comment]
Looks good, thanks for the PR!

**Comment by maoo** [comment]
> @finos-admin please fix cla bot

Dear @timkpaine , this is the expected behaviour of the CLA bot; it seems that @zemeolotu didn't configure the git client used to perform commits in the perspective repo; the comment above walks through few simple steps to help fixing it, please let me know if there's anything unclear.

Without such configuration, GitHub API doesn't return the GitHub ID of the commit's author; you can compare this PR on https://api.github.com/repos/finos/perspective/pulls/747/commits (note that `author` is null) with https://api.github.com/repos/finos/perspective/pulls/748/commits (where `author/login` is defined)

Hope this clarifies a bit more. You can find more info about FINOS contribution compliance requirements on our Wiki - https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements

**Pull request merged**
