### PR TITLE
Add Python `3.10`

### LINKED ISSUE #1682: Support python 3.10 on windows
pip install perspective-python fail on windows python 3.10 env, error message: 

```
  running build_ext
  setup.py:104: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    cmake_version = LooseVersion(
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      Visual Studio 15 2017

    could not find any instance of Visual Studio.
```

If I switch to python 3.9, pip install will success

### PR DESCRIPTION
**Pull request by texodus**
Fixes #1682

### CODE REVIEW

**Comment by texodus** [comment]
[Full CI build](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=3844&view=results)

**Comment by timkpaine** [comment]
https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=3867&view=results

**Comment by timkpaine** [comment]
```
0   libsystem_kernel.dylib        	       0x1848399b8 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18486ceb0 pthread_kill + 288
2   libsystem_c.dylib             	       0x184772ca4 raise + 32
3   libsystem_platform.dylib      	       0x1848844e4 _sigtramp + 56
4   libbinding.so                 	       0x1262c197c pybind11::str::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >() const + 72
5   libbinding.so                 	       0x1262c197c pybind11::str::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >() const + 72
6   libbinding.so                 	       0x126343714 perspective::binding::make_table_py(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long) + 7328
7   libbinding.so                 	       0x126332dc8 std::__1::shared_ptr<perspective::Table> pybind11::detail::argument_loader<pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long>::call_impl<std::__1::shared_ptr<perspective::Table>, std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, pybind11::detail::void_type>(std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>, pybind11::detail::void_type&&) && + 96
8   libbinding.so                 	       0x126332628 void pybind11::cpp_function::initialize<std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table>, pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long, pybind11::name, pybind11::scope, pybind11::sibling>(std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table> (*)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 68
9   libbinding.so                 	       0x1262c77ec pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3280
```

**Comment by timkpaine** [comment]
```
* thread #10, stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x00000001005a1a70 Python`PyBytes_FromStringAndSize + 288
    frame #1: 0x000000013a7eb69c libbinding.so`pybind11::str::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >(this=0x00000001711d7da0) const at pytypes.h:1100:46
    frame #2: 0x000000013a990948 libbinding.so`perspective::binding::make_table_py(table=t_val @ 0x00000001711d7dc0, accessor=t_data_accessor @ 0x00000001711d7db8, limit=4294967295, index=str @ 0x00000001711d7da0, op=OP_INSERT, is_update=true, is_arrow=true, is_csv=true, port_id=0) at table.cpp:262:59
    frame #3: 0x000000013a96934c libbinding.so`std::__1::shared_ptr<perspective::Table> pybind11::detail::argument_loader<pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long>::call_impl<std::__1::shared_ptr<perspective::Table>, std::__1::shared_ptr<perspective::Table> (this=0x00000001711d7eb0, f=(0x000060000301f638), (null)=std::__1::index_sequence<0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL> @ 0x00000001711d7de7, (null)=0x00000001711d7e16)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, pybind11::detail::void_type>(std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>, pybind11::detail::void_type&&) && at cast.h:1217:16
    frame #4: 0x000000013a968380 libbinding.so`std::__1::enable_if<!(std::is_void<std::__1::shared_ptr<perspective::Table> >::value), std::__1::shared_ptr<perspective::Table> >::type pybind11::detail::argument_loader<pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long>::call<std::__1::shared_ptr<perspective::Table>, pybind11::detail::void_type, std::__1::shared_ptr<perspective::Table> (this=0x00000001711d7eb0, f=(0x000060000301f638))(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long)>(std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long)) && at cast.h:1189:42
    frame #5: 0x000000013a9681d8 libbinding.so`void pybind11::cpp_function::initialize<std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table>, pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long, pybind11::name, pybind11::scope, pybind11::sibling>(this=0x00000001711d8530, call=0x00000001711d8530)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table> (*)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const at pybind11.h:233:52
    frame #6: 0x000000013a968104 libbinding.so`void pybind11::cpp_function::initialize<std::__1::shared_ptr<perspective::Table> (*&)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table>, pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long, pybind11::name, pybind11::scope, pybind11::sibling>(call=0x00000001711d8530)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), std::__1::shared_ptr<perspective::Table> (*)(pybind11::object, pybind11::object, unsigned int, pybind11::str, perspective::t_op, bool, bool, bool, unsigned long long), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) at pybind11.h:210:21
    frame #7: 0x000000013a7fce14 libbinding.so`pybind11::cpp_function::dispatcher(self=0x000000013a727900, args_in=0x000000013e87c9e0, kwargs_in=0x0000000000000000) at pybind11.h:814:30
    frame #8: 0x0000000100600874 Python`cfunction_call + 60
    frame #9: 0x00000001005ae038 Python`_PyObject_MakeTpCall + 136
    frame #10: 0x00000001006a9fe0 Python`call_function + 272
    frame #11: 0x00000001006a4ae0 Python`_PyEval_EvalFrameDefault + 32932
    frame #12: 0x000000010069b768 Python`_PyEval_Vector + 328
```

**Comment by timkpaine** [comment]
[Full CI Build](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=3875&view=results)

**Comment by timkpaine** [comment]
Debugging instructions (this is how I usually look for these things):

1. Build debug (`PSP_DEBUG=1 yarn build_python --python310`)
2. Run `lldb` (`lldb python3.10`)
3. Set breakpoints (e.g. `breakpoint set --file table.cpp --line 262`)
4. Run python code under `lldb` (e.g. put reproducer in `tmp.py` and run `run tmp.py`)

**Comment by timkpaine** [comment]
@texodus builds are passing but needs new dockerfiles

**Comment by texodus** [comment]
I get this docker error:
```
Step 19/48 : RUN cp -arf /opt/python/cp36-cp36m/* /usr/local/
 ---> Running in 26d832af574b
cp: `/opt/python/cp36-cp36m/bin/python3.6' and `/usr/local/bin/python3.6' are the same file
The command '/bin/sh -c cp -arf /opt/python/cp36-cp36m/* /usr/local/' returned a non-zero code: 1
```

**Comment by timkpaine** [comment]
closing for now, with the GHA work and rewrite of some of the build/lint/test scripts for python, this should be smaller and less noisy

**Pull request closed without merging**
