### PR TITLE
Fix readme badge

### PR DESCRIPTION
**Pull request by timkpaine**
Workflow was renamed from `build.yml` to `build.yaml`

### CODE REVIEW

**Comment by texodus** [comment]
This PR is branched from a commit that is not an ancestor of `master`.

**Comment by timkpaine** [comment]
image

The badge is still broken btw

**Comment by texodus** [comment]
> image
> 
> The badge is still broken btw

No it isn't, please check before you post

**Comment by timkpaine** [comment]
Yes it is, please check before you reply lol

**Comment by texodus** [comment]
Screenshot 2024-08-03 at 5 42 45 PM

https://github.com/finos/perspective/commit/976727da47ecfcfd94a64ae8d27eac530fd118ac#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R9

**Comment by timkpaine** [comment]
And what happens when you click on it?

From your very own diff, the link is broken!

Screenshot 2024-08-03 at 17 44 48

**Comment by texodus** [comment]
> > The **_badge_** is still broken btw 

You could've just said "The link doesn't work" instead of being obtuse. Regardless, still can't merge this out-of-tree PR.

**Pull request closed without merging**
