### PR TITLE
Spark bar

### PR DESCRIPTION
**Pull request by texodus**
sparkbar

### CODE REVIEW

**Comment by texodus** [comment]
w/negative bars
sparkbar2

**Comment by nmichaud** [comment]
Something looks strange in your last example, where you have bars on both the positive and negative sides.

**Comment by texodus** [comment]
@nmichaud Check the column headers for these columns - these are calculated columns (using new ExprTK lang) which filter +/- rows

**Comment by nmichaud** [comment]
Got it - I was thinking the filtering was on the aggregate value.

**Comment by ArashPartow** [comment]
@texodus  for single line conditional statements you could also use the function conditional, eg:

if ("Profit" < 0, "Profit", 0)

if ("Profit" > 0, "Profit", 0)

**Pull request merged**
