### PR TITLE
JupyterLab enhancements

### PR DESCRIPTION
**Pull request by timkpaine**
- Enhancements to perspective-python to support d3fc charts
- add filter configuration
- add plugin configuration

### CODE REVIEW

**Comment by timkpaine** [comment]
https://github.com/timkpaine/perspective-python/pull/69

**Comment by timkpaine** [comment]
Screen Shot 2019-05-12 at 7 12 59 PM

**Comment by timkpaine** [comment]
https://pypi.org/project/perspective-python/0.1.6/

**Comment by texodus** [comment]
Thanks for the PR, looks good!

**Pull request merged**
