### PR TITLE
fix: allow more icons to be overridden

### PR DESCRIPTION
**Pull request by kevinhinterlong**
Updates some icons to use css variables, and adds hover state to close/sort icons

### CODE REVIEW

**Comment by kevinhinterlong** [comment]
@maoo I've signed the CLA here https://github.com/finos/open-developer-platform/pull/291

**Comment by texodus** [comment]
@kevinhinterlong I wasn't waiting on the CLA :)  This PR is still in draft state, you need to click the "Ready for Review" button at the bottom when you're ready for this to be merged.

**Comment by kevinhinterlong** [comment]
> @kevinhinterlong I wasn't waiting on the CLA :) This PR is still in draft state, you need to click the "Ready for Review" button at the bottom when you're ready for this to be merged.

👍 updated, just wanted to make sure I wasn't missing anything for the CLA

**Comment by texodus** [comment]
Thanks for the PR @kevinhinterlong!  One minor tweak - I'd like to not hard-code more colors into the inline CSS, so I've reverted just the color changes and made the hover styles bacup to `inherit` when the variable is not set.  Closing in favor of #1763 which contains this PR's commit as well.

**Pull request closed without merging**
