### PR TITLE
prune win 2019 from ci, switch over to windows-2022 only

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by texodus** [comment]
@timkpaine Is this a draft or not?

[full build](https://github.com/finos/perspective/actions/runs/5846282109)

**Comment by timkpaine** [comment]
I wanted to make sure the full build ran, but it was failing due to the usual reasons (unrelated to this PR, though this PR will hopefully help). If the full build passes (any the only failures are the current known network / one tornado test) then its good to go

**Comment by texodus** [comment]
> [full build](https://github.com/finos/perspective/actions/runs/5846282109)

**Review by texodus — APPROVED** [review]
Thanks for the PR! Looks good!

**Pull request merged**
