### PR TITLE
Format numbers to avoid common label overlaps

### PR DESCRIPTION
**Pull request by 100starnight**
## Description
Long tick labels tend to overlap the axis labels (issue #1039); this PR updates the value formatter to avoid the most common instances of collision.

## Photos
axisTickLabelOverlapBug
axisTickLabelOverlapFix

### CODE REVIEW

**Review by raymondfx — APPROVED** [review]

**Review by jkusa — APPROVED** [review]

**Comment by 100starnight** [comment]
Hey @texodus I see the tests were completed successfully; just wanted to check in and see if this pr is just waiting for reviews or if there's another approach I should consider...?

**Comment by texodus** [comment]
@100starnight I appreciate the attention to this issue but this is not the correct fix.  The axis label container width (in this case for `linearAxis` types in the Y position) are not being calculated correctly (or at all - I don't know offhand).  Your fix just shortens the text generated within this container in.a specific case.  While this removes overlap in this specific case, the container is still the wrong width, so different data-extents/fonts/etc still will overlap.  Ergo, the PR "fixes" some cases and "breaks" others;  this is common symptom of fixes that wallpaper-over rendering issues with CSS.

A correct fix will make sure the axis container is the minimum bounding rectangle for the rendered labels.   I suspect the we'll need to implement something like the [bounds calculation for `ordinalAxis`](https://github.com/finos/perspective/blob/master/packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js#L249).

**Comment by 100starnight** [comment]
Hey @texodus! While I agree that this update doesn't address all of the bug cases, I do think it's a good quick win for a very common bad UI experience (as reported by our users & others who've tried to fix the bug before). Would you consider merging this change while I keep looking into it?

Honestly, even independent of the overlap issue, I think that re-evaluating the ticks' current level of precision is worthwhile - setting SI_MIN to 100,000 seems fairly reasonable and it's more readable than our current state

**Comment by 100starnight** [comment]
@texodus thoughts on above?

**Pull request closed without merging**
